#remote_theme: pages-themes/hacker@v0.2.0
plugins:
#- jekyll-remote-theme
- jekyll-feed # Add ATOM(RSS) feed

theme: minima
# Site basic
timezone: Europe/Amsterdam
title: "Tom's Blog"
description: "A blog site covering topics like low level programming, privacy, computers and more; RSS: **https://tomscheers.github.io/feed.xml**."
url: "https://tomscheers.github.io"

author: "Tom Scheers"
