theme: minima

# Site basics
timezone: Europe/Amsterdam
title: "Tom's Blog"
description: "A blog site covering topics like low level programming, privacy, computers and more"
url: "https://tomscheers.github.io"

# Author
author:
  name: "Tom Scheers"
  email: "tomscheers@outlook.com"

# Minima options
minima:
  skin: dark     
  social_links:
    - platform: github
      user_url: "https://github.com/tomScheers"

# Recommended plugins (work on GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
