remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed # Add ATOM(RSS) feed

# Site basic
timezone: Europe/Amsterdam
title: "Tom's Blog"
description: "A blog site covering topics like low level programming, privacy, computers and more."
rss: RSS
url: "https://tomscheers.github.io"

author: "Tom Scheers"
