version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: bash -c "gem install webrick && jekyll serve --force_polling --host 0.0.0.0 --port 4000"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
